# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cfff45a6a4c594436bb3cddb634a31a"
application_url = "https://search-paths-mumbai-ottawa.trycloudflare.com"
embedded = true
name = "demo-shopi"
handle = "demo-shopi-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "https://e608-113-160-81-90.ngrok-free.app/shopify-api-client/product/product_create"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "https://e608-113-160-81-90.ngrok-free.app/shopify-api-client/product/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://search-paths-mumbai-ottawa.trycloudflare.com/auth/callback",
  "https://search-paths-mumbai-ottawa.trycloudflare.com/auth/shopify/callback",
  "https://search-paths-mumbai-ottawa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
